In [1]:
import pandas as pd

In [ ]:
#creating data frames that store the csv files

In [2]:
d1 = pd.read_csv('TXDemo2015.csv')

In [3]:
d2 = pd.read_csv('TXDemo2016.csv')

In [5]:
d3 = pd.read_csv('DistrictDisparities2015.csv')

In [6]:
d4 = pd.read_csv('DistrictDisparities2016.csv')

In [57]:
#The number of Black or african american people is stored as su

In [59]:
su = sum(d1['BLACK OR AFRICAN AMERICAN'])

In [60]:
su

658578

In [10]:
d1

,DISTRICT,DISTNAME,DPETALLC,ASIAN,AMERICAN INDIAN OR ALASKA NAT,NATIVE HAWAIIAN/OTHER PACIFIC,HISPANIC/LATINO,BLACK OR AFRICAN AMERICAN,TWO OR MORE RACES,Special Education,WHITE,Economic Disadvantage
0,1902,CAYUGA ISD,577,2,0,0,36,27,31,76,477,210
1,1903,ELKHART ISD,1217,13,1,2,108,64,37,126,990,647
2,1904,FRANKSTON ISD,803,7,4,0,82,89,32,77,587,445
3,1906,NECHES ISD,370,1,0,0,41,29,5,41,291,156
4,1907,PALESTINE ISD,3352,30,46,3,1310,911,93,291,958,2457
5,1908,WESTWOOD ISD,1595,12,4,0,398,277,57,148,845,1019
6,1909,SLOCUM ISD,389,0,3,0,22,5,8,47,350,162
7,2901,ANDREWS ISD,4006,12,8,0,2672,60,60,256,1197,1462
8,3801,PINEYWOODS COMMUNITY ACADEMY,811,18,0,0,140,133,14,48,502,407
9,3902,HUDSON ISD,2816,25,25,0,647,191,36,199,1889,1498
10,3903,LUFKIN ISD,8322,141,16,8,3270,2413,166,873,2305,6149
11,3904,HUNTINGTON ISD,1755,1,8,0,115,29,40,168,1558,888
12,3905,DIBOLL ISD,1930,5,1,1,1038,231,30,212,619,1296
13,3906,ZAVALLA ISD,412,0,2,0,16,4,7,56,381,245
14,3907,CENTRAL ISD,1575,1,6,0,315,97,29,162,1124,836
15,4901,ARANSAS COUNTY ISD,3246,71,12,0,1304,48,77,282,1730,1801
16,5901,ARCHER CITY ISD,482,0,2,0,41,3,21,52,412,178
17,5902,HOLLIDAY ISD,901,0,2,0,61,2,15,81,818,212
18,5904,WINDTHORST ISD,458,0,5,0,130,0,1,34,319,158
19,6902,CLAUDE ISD,357,0,2,0,44,8,7,37,293,146
20,7901,CHARLOTTE ISD,513,0,0,0,446,1,3,52,62,356
21,7902,JOURDANTON ISD,1633,1,3,0,955,16,14,132,641,919
22,7904,LYTLE ISD,1720,0,8,3,1367,15,8,113,314,1228
23,7905,PLEASANTON ISD,3568,14,7,0,2483,17,28,256,1013,1819
24,7906,POTEET ISD,1742,1,5,0,1475,5,8,134,245,1336
25,8901,BELLVILLE ISD,2159,6,6,0,610,218,47,172,1267,995
26,8902,SEALY ISD,2793,11,5,2,1309,287,53,226,1122,1583
27,8903,BRAZOS ISD,836,5,0,0,398,83,18,56,329,474
28,9901,MULESHOE ISD,1423,9,0,0,1182,7,1,153,221,1209
29,10901,MEDINA ISD,268,0,1,0,65,4,8,31,188,162
...,...,...,...,...,...,...,...,...,...,...,...,...
1189,246912,THRALL ISD,654,1,3,1,183,15,18,60,430,213
1190,246913,LEANDER ISD,36105,2130,108,72,8737,1371,1408,3502,22312,7112
1191,246914,COUPLAND ISD,142,0,2,0,39,0,6,6,91,47
1192,247901,FLORESVILLE ISD,3935,11,15,0,2561,51,51,417,1243,2010
1193,247903,LA VERNIA ISD,3181,3,15,0,868,28,57,286,2207,750
1194,247904,POTH ISD,823,0,1,0,377,4,4,61,433,302
1195,247906,STOCKDALE ISD,832,0,0,0,390,6,9,123,424,426
1196,248901,KERMIT ISD,1451,7,2,0,1123,27,10,127,280,944
1197,248902,WINK-LOVING ISD,407,0,2,0,144,10,4,30,247,159
1198,249901,ALVORD ISD,692,0,0,0,100,4,8,62,579,222
1199,249902,BOYD ISD,1153,3,13,1,164,10,33,79,925,536
1200,249903,BRIDGEPORT ISD,2080,6,12,0,1042,14,33,180,969,1171
1201,249904,CHICO ISD,604,0,6,0,143,6,13,50,434,349
1202,249905,DECATUR ISD,2999,23,17,2,1007,38,38,278,1868,1331
1203,249906,PARADISE ISD,1127,2,4,0,134,5,13,119,965,330
1204,249908,SLIDELL ISD,249,0,1,0,66,1,0,17,178,121
1205,250902,HAWKINS ISD,736,0,2,3,35,77,27,74,590,431
1206,250903,MINEOLA ISD,1587,20,6,1,453,114,52,101,939,904
1207,250904,QUITMAN ISD,1098,2,5,2,185,26,35,110,841,579
1208,250905,YANTIS ISD,349,0,1,0,83,3,11,16,250,204
1209,250906,ALBA-GOLDEN ISD,853,5,1,0,98,3,9,73,736,430
1210,250907,WINNSBORO ISD,1448,18,5,1,205,24,41,110,1149,760
1211,251901,DENVER CITY ISD,1754,7,3,1,1397,15,12,96,317,850
1212,251902,PLAINS ISD,454,0,0,0,296,0,0,30,157,287
1213,252901,GRAHAM ISD,2494,9,17,2,760,27,29,244,1646,1354
1214,252902,NEWCASTLE ISD,210,0,0,1,21,0,2,23,185,112
1215,252903,OLNEY ISD,725,2,2,0,265,15,28,100,411,450
1216,253901,ZAPATA COUNTY ISD,3677,3,0,0,3640,0,0,257,33,2912
1217,254901,CRYSTAL CITY ISD,2011,4,0,0,1966,8,4,170,26,1429
1218,254902,LA PRYOR ISD,483,0,0,0,454,0,0,50,27,424

In [11]:
sum(d1['BLACK OR AFRICAN AMERICAN'])

658578

In [61]:
#seperating out the black or african american people category into the dataframe- 'dafr'

In [62]:
dafr = d4.loc[d4['HEADING NAME'] == 'BLACK OR AFRICAN AMERICAN']

In [67]:
# storing the number of punishments by Black or african american people in 'b' and the total Black or african american people in 'a'

In [63]:
a = sum(d2['BLACK OR AFRICAN AMERICAN'])

In [64]:
b = sum(dafr['Group Punishments'])

In [65]:
perc = (b/a)*100

In [70]:
#perc has the number of Black or african american people who were punished in Texas for the year 2016

In [71]:
perc

72.303180304296987

In [68]:
#change d3 and d4 to eliminate unrequired heading names like special education and so on

In [35]:
dx = d3.loc[(d3['HEADING NAME'] != 'Economic Disadvantage') & (d3['HEADING NAME'] != 'Special Education') & (d3['HEADING NAME'] != 'TWO OR MORE RACES')]

In [72]:
dxx = d4.loc[(d4['HEADING NAME'] != 'Economic Disadvantage') & (d4['HEADING NAME'] != 'Special Education') & (d4['HEADING NAME'] != 'TWO OR MORE RACES')]

In [73]:
#the data frame 'aa' holds the total people who were punished in both the years

In [49]:
aa = dx['Group Punishments'].sum() + dxx['Group Punishments'].sum()

In [74]:
#the data frame 'aa' holds the total people  in both the years

In [50]:
bb = d1['DPETALLC'].sum() + d2['DPETALLC'].sum()

In [75]:
# The percentage of folks got punished as compared to the overall population over both the years is stored in 'totalperc'

In [76]:
totalperc = (aa/bb)*100

In [77]:
totalperc

32.181513960524342

In [55]:
perc

72.303180304296987

In [79]:
# I also made an observation that for some of the districts the column 'DPETALLC' does not hold the exact sum of 'ASIAN'

In [80]:
#'AMERICAN INDIAN OR ALASKA NAT','HISPANIC/LATINO' AND 'WHITE'

In [78]:
d1

,DISTRICT,DISTNAME,DPETALLC,ASIAN,AMERICAN INDIAN OR ALASKA NAT,NATIVE HAWAIIAN/OTHER PACIFIC,HISPANIC/LATINO,BLACK OR AFRICAN AMERICAN,TWO OR MORE RACES,Special Education,WHITE,Economic Disadvantage
0,1902,CAYUGA ISD,577,2,0,0,36,27,31,76,477,210
1,1903,ELKHART ISD,1217,13,1,2,108,64,37,126,990,647
2,1904,FRANKSTON ISD,803,7,4,0,82,89,32,77,587,445
3,1906,NECHES ISD,370,1,0,0,41,29,5,41,291,156
4,1907,PALESTINE ISD,3352,30,46,3,1310,911,93,291,958,2457
5,1908,WESTWOOD ISD,1595,12,4,0,398,277,57,148,845,1019
6,1909,SLOCUM ISD,389,0,3,0,22,5,8,47,350,162
7,2901,ANDREWS ISD,4006,12,8,0,2672,60,60,256,1197,1462
8,3801,PINEYWOODS COMMUNITY ACADEMY,811,18,0,0,140,133,14,48,502,407
9,3902,HUDSON ISD,2816,25,25,0,647,191,36,199,1889,1498
10,3903,LUFKIN ISD,8322,141,16,8,3270,2413,166,873,2305,6149
11,3904,HUNTINGTON ISD,1755,1,8,0,115,29,40,168,1558,888
12,3905,DIBOLL ISD,1930,5,1,1,1038,231,30,212,619,1296
13,3906,ZAVALLA ISD,412,0,2,0,16,4,7,56,381,245
14,3907,CENTRAL ISD,1575,1,6,0,315,97,29,162,1124,836
15,4901,ARANSAS COUNTY ISD,3246,71,12,0,1304,48,77,282,1730,1801
16,5901,ARCHER CITY ISD,482,0,2,0,41,3,21,52,412,178
17,5902,HOLLIDAY ISD,901,0,2,0,61,2,15,81,818,212
18,5904,WINDTHORST ISD,458,0,5,0,130,0,1,34,319,158
19,6902,CLAUDE ISD,357,0,2,0,44,8,7,37,293,146
20,7901,CHARLOTTE ISD,513,0,0,0,446,1,3,52,62,356
21,7902,JOURDANTON ISD,1633,1,3,0,955,16,14,132,641,919
22,7904,LYTLE ISD,1720,0,8,3,1367,15,8,113,314,1228
23,7905,PLEASANTON ISD,3568,14,7,0,2483,17,28,256,1013,1819
24,7906,POTEET ISD,1742,1,5,0,1475,5,8,134,245,1336
25,8901,BELLVILLE ISD,2159,6,6,0,610,218,47,172,1267,995
26,8902,SEALY ISD,2793,11,5,2,1309,287,53,226,1122,1583
27,8903,BRAZOS ISD,836,5,0,0,398,83,18,56,329,474
28,9901,MULESHOE ISD,1423,9,0,0,1182,7,1,153,221,1209
29,10901,MEDINA ISD,268,0,1,0,65,4,8,31,188,162
...,...,...,...,...,...,...,...,...,...,...,...,...
1189,246912,THRALL ISD,654,1,3,1,183,15,18,60,430,213
1190,246913,LEANDER ISD,36105,2130,108,72,8737,1371,1408,3502,22312,7112
1191,246914,COUPLAND ISD,142,0,2,0,39,0,6,6,91,47
1192,247901,FLORESVILLE ISD,3935,11,15,0,2561,51,51,417,1243,2010
1193,247903,LA VERNIA ISD,3181,3,15,0,868,28,57,286,2207,750
1194,247904,POTH ISD,823,0,1,0,377,4,4,61,433,302
1195,247906,STOCKDALE ISD,832,0,0,0,390,6,9,123,424,426
1196,248901,KERMIT ISD,1451,7,2,0,1123,27,10,127,280,944
1197,248902,WINK-LOVING ISD,407,0,2,0,144,10,4,30,247,159
1198,249901,ALVORD ISD,692,0,0,0,100,4,8,62,579,222
1199,249902,BOYD ISD,1153,3,13,1,164,10,33,79,925,536
1200,249903,BRIDGEPORT ISD,2080,6,12,0,1042,14,33,180,969,1171
1201,249904,CHICO ISD,604,0,6,0,143,6,13,50,434,349
1202,249905,DECATUR ISD,2999,23,17,2,1007,38,38,278,1868,1331
1203,249906,PARADISE ISD,1127,2,4,0,134,5,13,119,965,330
1204,249908,SLIDELL ISD,249,0,1,0,66,1,0,17,178,121
1205,250902,HAWKINS ISD,736,0,2,3,35,77,27,74,590,431
1206,250903,MINEOLA ISD,1587,20,6,1,453,114,52,101,939,904
1207,250904,QUITMAN ISD,1098,2,5,2,185,26,35,110,841,579
1208,250905,YANTIS ISD,349,0,1,0,83,3,11,16,250,204
1209,250906,ALBA-GOLDEN ISD,853,5,1,0,98,3,9,73,736,430
1210,250907,WINNSBORO ISD,1448,18,5,1,205,24,41,110,1149,760
1211,251901,DENVER CITY ISD,1754,7,3,1,1397,15,12,96,317,850
1212,251902,PLAINS ISD,454,0,0,0,296,0,0,30,157,287
1213,252901,GRAHAM ISD,2494,9,17,2,760,27,29,244,1646,1354
1214,252902,NEWCASTLE ISD,210,0,0,1,21,0,2,23,185,112
1215,252903,OLNEY ISD,725,2,2,0,265,15,28,100,411,450
1216,253901,ZAPATA COUNTY ISD,3677,3,0,0,3640,0,0,257,33,2912
1217,254901,CRYSTAL CITY ISD,2011,4,0,0,1966,8,4,170,26,1429
1218,254902,LA PRYOR ISD,483,0,0,0,454,0,0,50,27,424